name: Deploy Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          ls -la ~/.ssh

      - name: Copy files to server
        env:
          REMOTE_USER: ${{ secrets.PRD_USER }}
          REMOTE_HOST: ${{ secrets.PRD_HOST }}
          REMOTE_PATH: ${{ secrets.PRD_PATH }}
        run: |
          rsync -avz --exclude-from='.transferignore' --delete -e "ssh " ./ $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH || { echo "rsync failed with exit code $?"; exit 1; }

      - name: Run Install
        env:
          REMOTE_USER: ${{ secrets.PRD_USER }}
          REMOTE_HOST: ${{ secrets.PRD_HOST }}
          REMOTE_PATH: ${{ secrets.PRD_PATH }}
        run: |
          ssh $REMOTE_USER@$REMOTE_HOST "cd $REMOTE_PATH && pm2 stop index.mjs && pm2 flush && npm install && pm2 start index.mjs"
